[package]
name = "tree-git"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tree-core = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
tempfile = { workspace = true }
async-trait = { workspace = true }
